# Generated by Django 3.0.4 on 2020-07-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobInfo',
            fields=[
                ('job_info_seqno', models.AutoField(primary_key=True, serialize=False)),
                ('job_info_name', models.CharField(max_length=150)),
                ('job_info_detail', models.CharField(blank=True, max_length=300, null=True)),
                ('job_info_note', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'job_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JobServerMap',
            fields=[
                ('job_server_map_seqno', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_info_seqno', models.PositiveIntegerField()),
                ('server_list_seqno', models.PositiveSmallIntegerField()),
                ('use_yn', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'job_server_map',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('server_list_seqno', models.SmallAutoField(primary_key=True, serialize=False)),
                ('svr', models.CharField(blank=True, max_length=30, null=True)),
                ('usg', models.CharField(blank=True, max_length=100, null=True)),
                ('port1', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ip1', models.CharField(blank=True, max_length=15, null=True)),
                ('ip2', models.CharField(blank=True, max_length=15, null=True)),
                ('priority', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'server_list',
                'managed': False,
            },
        ),
    ]
