# Generated by Django 3.0.4 on 2020-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(default='0000000000000001', max_length=16)),
                ('faq_type', models.CharField(default='999', max_length=10)),
                ('faq_question', models.TextField(default='질문')),
                ('faq_answer', models.TextField(default='답변')),
            ],
            options={
                'db_table': 'testing_faq',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('read', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'testing_post',
            },
        ),
    ]
