# Generated by Django 3.0.6 on 2020-05-16 13:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_create_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('account_update_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('account_end_dt', models.DateTimeField(null=True)),
                ('account_requestor', models.CharField(blank=True, default='', max_length=100)),
                ('account_devteam', models.CharField(blank=True, default='', max_length=100)),
                ('account_svr', models.CharField(blank=True, default='', max_length=100)),
                ('account_user', models.CharField(default='', max_length=50)),
                ('account_host', models.CharField(default='', max_length=100)),
                ('account_pass', models.CharField(default='', max_length=100)),
                ('account_hash', models.CharField(default='', max_length=100)),
                ('account_grant', models.CharField(blank=True, default='', max_length=100)),
                ('account_grant_with', models.CharField(blank=True, default='N', max_length=100)),
                ('account_db', models.CharField(blank=True, default='', max_length=100)),
                ('account_table', models.CharField(blank=True, default='', max_length=100)),
                ('account_info', models.CharField(blank=True, default='', max_length=100)),
                ('account_sql', models.CharField(blank=True, default='', max_length=200)),
                ('account_url', models.CharField(blank=True, default='', max_length=100)),
                ('account_del_yn', models.CharField(blank=True, default='N', max_length=100)),
                ('account_del_dt', models.DateTimeField(null=True)),
                ('account_del_reason', models.CharField(blank=True, default='', max_length=100)),
                ('account_del_note', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account_hash',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_encrypt', models.CharField(blank=True, default='', max_length=100, unique=True)),
                ('password_hash', models.CharField(blank=True, default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='AccountRepository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_dt', models.DateTimeField(default=datetime.datetime.now)),
                ('repository_team', models.CharField(blank=True, default='', max_length=20)),
                ('repository_name', models.CharField(blank=True, default='', max_length=100)),
                ('repository_url', models.CharField(blank=True, default='', max_length=250)),
                ('account_user', models.CharField(blank=True, default='', max_length=50)),
                ('url', models.CharField(blank=True, default='', max_length=100)),
                ('info', models.CharField(blank=True, default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faq_id', models.CharField(default='0000000000000001', max_length=16)),
                ('faq_type', models.CharField(default='999', max_length=10)),
                ('faq_question', models.TextField(default='질문')),
                ('faq_answer', models.TextField(default='답변')),
            ],
        ),
    ]
