# Generated by Django 3.0.4 on 2020-07-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_hash',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterModelTable(
            name='account',
            table='account_account',
        ),
        migrations.AlterModelTable(
            name='account_hash',
            table='account_hash',
        ),
        migrations.AlterModelTable(
            name='accountrepository',
            table='account_repository',
        ),
        migrations.AlterModelTable(
            name='faq',
            table='account_faq',
        ),
    ]
