# Generated by Django 3.0.6 on 2020-07-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200710_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_del_note',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_del_reason',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
