# Generated by Django 3.0.4 on 2020-08-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200720_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_sql',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
